### ISSUE TITLE
find by nummeric needs string

### ISSUE THREAD

**Issue by Student007** [techfort/LokiJS#142] opened 2015-04-14 08:31 UTC
Hi Joe,
first let me thank you for creating that awesome in-memory database :-)

I think I found a minor bug about to find entries. You can reproduce it by creating a small db with an index by e.g. coordinates x and y, what are numbers.
```
var collection = db.addCollection('treasure', {indices: ['x', 'y'] });
collection.insert({
  x: 1,
  y: 1,
  text: 'here is the treasure'
},
{
  x: 20,
  y: 10,
 text: 'here a stupid one was digging into the ground'
});
```
If you try to find it by
```
collection.find({'x': 1, 'y':1}); // doesn't whistleblow that it was right
```
you will get en empty result (without no comment about wrong way to ask for).

If you do right, you will find an entry:
```
collection.find({'x': '20', 'y': '10'});
```
There are several ideas about preventing trouble for developers:
If you want to do it more performance supporting, a simple warning about inserting numbers instead of text would be right.
Else you could convert the find request to strings in general.
-Dan

**Comment by techfort** [comment] 2015-04-14 08:46
Thanks Dan for catching this, will look into this asap!

**Comment by techfort** [comment] 2015-04-24 12:22
@Student007 talking to @obeliskos i actually found that the problem doesn't reside in the fact that you need to pass a string for a number, but the fact that you're using a slightly wrong syntax in the find (which I had not noticed!): instead of `find({x: 1, y: 1})` you need to do `find({x: 1}, {y:1})` the difference being that you need to pass two distinct object queries, not a single object with two properties.
I actually couldn't reproduce the issue because i was using the correct syntax (force of habit really...), so I was a bit confused, and i can confirm Loki behaves as expected. Closing this but let me know if you encounter any more problems (and of course feel free to re-open this if you feel there's an issue).

**Closed by techfort** 2015-04-24 12:22 UTC

**Comment by obeliskos** [comment] 2015-04-24 21:12
Yes I think the insert should read : 
```javascript
collection.insert([
  { x: 1, y: 1},
  { x: 20, y: 10 }
]);
```
and your find should look like : 
```javascript
collection.find({ 
  '$and': [
    {'x': 20}, {'y': 10}
  ]
});
```

**Comment by retorquere** [comment] 2015-05-30 14:14
I would propose to make this very explicit in the documentation. I too was using this approach to finding an object using a multi-property object, and I was getting what I thought were random results back :( 

Any particular reason not to support this way of finding objects? It seems so natural.

**Comment by retorquere** [comment] 2015-05-30 14:34
Would this work?

    loki.Collection.findObject = function(template) {
      var k, obj1, query;
      query = [];
      for (k in template) {
        if (! template.hasOwnProperty(k)) continue;
        query.push((
          obj1 = {},
          obj1[k] = template[k],
          obj1
        ));
      }
      return this.findOne({
        '$and': query
      });
    }

**Comment by techfort** [comment] 2015-05-30 18:55
@retorquere i'm all for a PR if you want to submit one. Your trick is neat, the important thing is to utilize find (which you do!) so to leverage indexes.

**Comment by retorquere** [comment] 2015-05-30 19:10
https://github.com/techfort/LokiJS/pull/155

**Comment by retorquere** [comment] 2015-05-30 19:12
I take it then this:

    keys.find({citekey: { '$in': citekeys }, libraryID: libraryID}))

is also not OK? Would that then be

    @keys.find({'$and' : [{citekey: { '$in': citekeys }}, {libraryID: libraryID}]})

**Comment by techfort** [comment] 2015-05-30 19:15
that's correct.

**Comment by retorquere** [comment] 2015-05-30 19:30
BTW, don't know where else to leave the praise, but LokiJS has provided me with a very clean solution to  safely implement DB caching in my app. I'm seeing 10-20x speedups. Very happy.

**Comment by techfort** [comment] 2015-05-30 19:36
Thanks! DB caching has been a very common use case for Loki, and I envisage
doing the same on the server side, with loki providing a nodejs native
alternative to redis, with the added advantage of providing dynamic views
and queries. I have prototypes of a server loki running as a front for
mongo or rethinkdb and it works quite well. Thanks a lot anyway!

**Comment by retorquere** [comment] 2015-05-30 19:41
One thing that lok does that I haven't yet seem elsewhere is triggers (`.on`) and the changes list. Makes it super-easy to keep consistency between collections, and I have a background timer that causes the cache to flush ever minute, so it's very save.

**Comment by techfort** [comment] 2015-05-30 19:43
have you got a gist for that - sounds interesting!

**Comment by retorquere** [comment] 2015-05-30 20:41
I've put up a gist at https://gist.github.com/anonymous/e62cc4e401921506a6dc, but mind that this is Firefox privileged ("chrome") javascript -- I don't know whether the idle observer is available in regular JS. In any case, settimeout is, and if you want to get really funky, you could just hand off the flush to a web worker, as long as the actual flush is done over web services. 

In my case, the flush is to sqlite, and even just batching the flush to a 5 second interval has made a huge difference. I am doing fairly naive caching, as in, I don't do inspections to see if something needs to be loaded from the real storage; at startup, I read everything I need cache for into loki, and after that, all reads and writes go to loki only. At shutdown, idle events, and every 5 minutes just to be sure, I flush the collected changes out to sqlite. Made the difference between slow-but-usable and being the fastest Zotero translator by a factor of 10. It has allowed me to do on-demand background exports of bibliographies -- had been done before, but not where you could casually have 10 different of them going.
