### ISSUE TITLE
bulk remove very slow

### ISSUE THREAD

**Issue by z543** [techfort/LokiJS#663] opened 2018-03-20 00:18 UTC
I bulk remove item using following code

the speed is very fast when size of items less than 50000 (approximate)
and it become very very very slow when size of items large than 60000 (approximate)

50000 items: 146 ms
60000 items: 14274 ms

CPU: Intel Core2 Duo E8400 3GHz
RAM: 8GB
Windows 7 x64
Chrome 67.0.3371.0 (Official Build) dev (64-bit)

```js
const docs = [
  { name: 'mjolnir', owner: 'thor', maker: 'dwarves' },
  { name: 'gungnir', owner: 'odin', maker: 'elves' },
  { name: 'tyrfing', owner: 'Svafrlami', maker: 'dwarves' },
  { name: 'draupnir', owner: 'odin', maker: 'elves' },
]
var db = new loki('sandbox.db')
// Add a collection to the database
var items = db.addCollection('items')

function addLokiItems(items, title) {
  console.time(title)
  for (var i = 0; i < 50000; i++) {
    items.insert({ ...docs[0], data: Math.random() })
  }
  console.timeEnd(title)
}

addLokiItems(items, 'loki-add mem')

function removeLokiItems(items, title) {
  console.time(title)
  var data = items.data
  var idIndex=items.idIndex
  items.findAndRemove({$loki: { '$gte' : 10 }})
  console.timeEnd(title)
}
removeLokiItems(items, 'loki-remove mem')
```

**Comment by Viatorus** [comment] 2018-03-20 07:27
Good catch.

I tried it out and it turned out that `Collection.remove` takes sometimes much longer.
![collection-remove](https://user-images.githubusercontent.com/3637911/37640743-4ee67956-2c17-11e8-8bd0-6772763cd4cf.png)

Using non adaptive binary indices on `$loki` speeds up the remove:

```js
var items = db.addCollection('items', {indices: ["$loki"], adaptiveBinaryIndices: false}) 
```

The bottleneck is the `slice` operation for the data and id index array. Maybe we can improve this somehow.

**Comment by obeliskos** [comment] 2018-03-20 09:51
Not entirely sure the fix I just commited will work with non-synthentic benchmarks like the above but assuming that your doc array is ordered similary to how they are ordered in the data array, the above seems to help significantly....

The main expense is the slice as mentioned, and in the above case reverse iterating... maybe we can force a sort on $loki before reverse iterating.

**Comment by z543** [comment] 2018-03-20 11:51
like this?, but it make no difference
```js
    items
      .chain()
      .find({ type: { $ne: 1 } })
      .simplesort('$loki')
      .remove()
```

**Comment by obeliskos** [comment] 2018-03-20 11:59
The simplesort isn't useful in the above because the find op will ensure that the results are sorted by loki.

In my 'worst-case' testing i was doing something like : 
```javascript
var results = items.find({$loki: { '$gte' : 10 }});
results = results.reverse();
items.remove(results);
```
That basically negates our array reversal so performance is as bad as before...

I can look into adding the forced array.sort on loki property maybe tonight but that will only help if your array is constructed/ordered randomly or in reverse.

**Comment by obeliskos** [comment] 2018-03-21 00:30
I am a little uncertain about the best way to do this and one that will be easily ported to lokijs2 so let me know if you have any comments.  Obviously if they go through findAndRemove, the following is irrelevant since they will be sorted by loki, but I am considering the case were perhaps they are constructing the array themselves or receiving it externally.

Lokijs, being in maintenance mode, technically allows the following items to be passed to collection.remove() : 
- a document
- a $loki id
- an array of documents
- an array of $loki ids
- any array of any mixture of documents and $loki ids

So obviously best practice would eliminate the last one but there is a possibility someone is using that.  So I can test typeof for the first item in the array and assume they are all of that type and if they are documents I use javascript sort function comparing $loki ids and if the first element is a number i just use native array sort which handles primitive types natively.  

That seems like bad practice so another thought is that we might expose Util and add a sort method which they can easily call, such as : 
```javascript
results.sort(loki.Util.lokiIdSortFunction);
```

None of those ways seem extremely optimal so I may leave this for the user to sort themselves if they are constructing or receiving the array which they want to batch remove.

Any thoughts or objections to this (not sorting within the remove function)?

**Comment by z543** [comment] 2018-03-21 07:50
sort not really solve the problem, 

```js
//insert items
for (var i = 0; i < count; i++) {
  items.insert({ ...docs[0], data: Math.random(), id: i, type: Math.round(Math.random() * 2) })
...
// do something...
...
//remove items where type!==1
items.findAndRemove({ type: { $ne: 1 } })
}
```

**Comment by obeliskos** [comment] 2018-03-21 09:57
I've not yet had time to test your above use case (maybe tonight) but you reminded me that : 

- if your find is based on binary index filtering, the order is likely to be the index ordering rather than $loki ordering (which currently would require sorting on $loki for optimal remove() performance.  
- resultset remove accepts no parameters and could easily perform a $loki sort before passing filtered docs into collection.remove()

So I don't know why the above would be slower... our default $gte should be slower than our default $ne op and both should do a full array scan unless there is indexing involved... in which case the $gte can leverage but seems the $ne cannot (oversight?).  I'll look into more later but thinking user can either do : 
```javascript
// once we add logic to resultset remove to sort first
items.chain().find({ type: { $ne: 1 }}).remove();
```
or : 
```javascript
function lokiObjectSort (obj1, obj2) {
  if (obj1.$loki === obj2.$loki) return 0;
  if (obj1.$loki > obj2.$loki) return 1;
  if (obj1.$loki < obj2.$loki) return -1;
}

var results = items.find({ type: { $ne: 1 }});
results.sort(lokiObjectSort);
items.remove(results);
```

**Comment by z543** [comment] 2018-03-21 14:28
I try using lokiObjectSort, which make no difference

**Comment by obeliskos** [comment] 2018-03-23 09:03
So I have done testing and discovered what I believe are further optimizations that I will look at implementing over the weekend.

I believe the previous commit does help but mainly when you are removing contiguous elements near end of array.  As more and more elements need to be shifted down for every individual remove, the cost builds up exponentially.  

My current approach is to add removeBatch and use hash object along with single array filter() rather than many individual calls to array slice().  That seems to yield significant improvements, I will add in all requisite safety checks and dynamic view / binary index notifications and verify performance is still significantly better.

**Comment by obeliskos** [comment] 2018-03-23 19:04
I have checked in an optimized algorithm for batch removes, which is currently tied into chained removes.

To utilize/test performance with that you might do something like : 
```javascript
coll.chain().find({data: { $ne: 2 }}).remove();
```

I am employing an array intersection algorithm similar to resulset simplesort() optimization made recently which replaces array slicing for each document with array filter() on data and idIndex arrays.

If DynamicViews or binary indices are involved, they will be notified of all removals.

@Viatorus (and all) :
I am considering not emitting 'delete' events for any of the documents, and the current new code path does not at the moment.  If you do batch removes, you should notify yourself.  If anyone disagrees, feel free to comment.

I will next look into retrofitting this new code path with the collection.remove() function.  I will need to test for arrays, and if user passes in (batch) array I will convert that array to what is expected of the new internal method.  Typescript definitions should not need to be changed.

**Comment by z543** [comment] 2018-03-24 03:56
It's really fast now  :+1: 

and I think it's only support $eq, $aeq, $lt, $lte, $gt, $gte, $between, $in,
not support $ne ...
right?

**Comment by obeliskos** [comment] 2018-03-24 10:49
Great :)

I have updated coll.remove() to use new optimized code path when passed a branch, so all methods of removing more than one document at a time (batch) should be optimized now.

You can use any of the ops in your find() or findAndRemove() calls.  Only $eq,$aeq,$lt,$lte,$gt,$between,$in can leverage binary indices to further speed up the 'find' part but all ops are supported.  

You should only need to add binary indices if your queries are expensive and for the examples you describe above (findAndRemove), the find() part of that was not expensive but the remove() part was... but that is also not expensive now that is optimized.

**Comment by Viatorus** [comment] 2018-03-24 11:34
Great work again!

I just thought of adding $ne to binary indices since it is the negation of
$eq?

**Comment by z543** [comment] 2018-03-24 14:00
total 50000 items 

```js
items.chain().find({type: { $eq: 1 }}).remove()  // 28 ms       
items.chain().find({type: { $ne: 1 }}).remove()  // 8856 ms   
```
why?

**Comment by obeliskos** [comment] 2018-03-24 14:36
@z543 , the optimizations I have just added are only available on github branch and will not hit npm until a 1.5.4 release which we are not yet ready to perform.   You might also clone the repo and edit/run the new benchmark_remove.js to verify performance.

@Viatorus, Our current $ne op uses strict inequality.  Our $eq op uses two phases, first abstract (leveraging indexes) and then second phase where we array scan and invoke strict $eq check :  
https://github.com/techfort/LokiJS/blob/402b86dd3854d1af74ff04f5d52870ca8f735de3/src/lokijs.js#L560-L573

So if you only care about abstract equality on an indexed op, $aeq will be faster.  My thinking is that, in general the number of results that are returned for $eq ops are less than $ne ops and that adding a following linear scan might be just as expensive as single (unindexed) linear scan.  Maybe a new indexable abstract version of that op?

For LokiJS2, we should probably rethink our op organization, and allow different 'modes' for binary indexing... I will open up a LokiJS2 issue to have discussion on how that might take shape.

**Comment by z543** [comment] 2018-03-26 23:21
@obeliskos 
> I am considering not emitting 'delete' events for any of the documents, and the current new code path does not at the moment. If you do batch removes, you should notify yourself. If anyone disagrees, feel free to comment.

Does it mean that DynamicView won't get notify ? and can't get correct result after batch removes ?

**Comment by obeliskos** [comment] 2018-03-27 08:42
DynamicViews and binary indices will be notified...

I had originally intended not to emit events because it was slowing down the batch remove even if there were no listeners, but I added that back in and only emit 'delete' events (1 emit for every object) if there are listeners to receive.  

> For lokijs2 we should probably emit a single event for the batch, possibly passing the entire array of docs that have been removed.

The only difference in behavior of new remove() functionality and old remove() functionality is that all the emitted events will be fired after all docs have been removed, instead of removing one at a time and firing after each.

**Comment by z543** [comment] 2018-03-27 10:52
in the last statement, 
console.log(results)   // expect empty array, but 3 items found

same result when using the latest code and Loki Sandbox 
Is it a bug, or something wrong with my code?

```js
    const docs = [
      { type: 0, name: 'mjolnir', owner: 'thor', maker: 'dwarves' },
      { type: 1, name: 'gungnir', owner: 'odin', maker: 'elves' },
      { type: 0, name: 'tyrfing', owner: 'Svafrlami', maker: 'dwarves' },
      { type: 1, name: 'draupnir', owner: 'odin', maker: 'elves' },
      { type: 0, name: 'a-mjolnir', owner: 'thor', maker: 'dwarves' },
      { type: 1, name: 'b-gungnir', owner: 'odin', maker: 'elves' },
      { type: 0, name: 'c-tyrfing', owner: 'Svafrlami', maker: 'dwarves' },
      { type: 1, name: 'd-draupnir', owner: 'odin', maker: 'elves' },
    ]
    var items = db.addCollection('xxx', {
      indices: ['type'],
    })
    var mydv = items.addDynamicView('test', { persistent: false }) // default is non-persistent
    items.insert(docs)
    var results = mydv.data()
    mydv.applyFind({ type: 0 })
    results = mydv.data()
    var item = items.findOne({ type: { $ne: 1 } })
    items.remove(item)
    results = mydv.data()
    items.findAndRemove({ type: { $ne: 1 } })
    results = mydv.data()
    console.log(results)   // expect empty array, but 3 items found
```

**Comment by Viatorus** [comment] 2018-03-28 07:54
@obeliskos 
The problem is located here:
https://github.com/techfort/LokiJS/blob/402b86dd3854d1af74ff04f5d52870ca8f735de3/src/lokijs.js#L5901-L5920

I think `didx` and `idx` are mixed up.

**Comment by obeliskos** [comment] 2018-03-28 09:14
Thanks, yes I found that bug but fixing that showed issues with the 'notifying' of dynamic views and indices when batches are involved.  I will look at enhancing those notifications to support working with batches tonight or tomorrow and see about updating unit tests to better cover batch removes when dynamic views and indices are involved.

**Comment by obeliskos** [comment] 2018-03-30 09:16
Sorry it's taken awhile, barely had time to look at this... 

I think I have found that there were only issues with dynamicviews (and not binary indices) and their being notified of batch removes.

I think I have fixed the dynamic view behavior you describe above and this can be verified on our (live) [LokiJS sandbox](https://rawgit.com/techfort/LokiJS/master/examples/sandbox/LokiSandbox.htm)

I did add some unit test coverage but will probably want to do more testing over the weekend... feel free to test yourself and let me know if you find any issues.  Had to rewrite the way the dynamic view internal resultset 'shifts down' its internal filteredrow (datapositions) as each removed document requires adjusting them.

**Comment by obeliskos** [comment] 2018-03-31 18:46
Further testing indicated that rework was needed for binary index notification of batch removes.  That has been done and seems to satisfy my initial testing and unit tests.  

I believe this to be complete now, let me know if you find otherwise.

**Closed** 2018-04-28 08:42 UTC
