### ISSUE TITLE
collection.update doesn't return the object

### ISSUE THREAD

**Issue by jpablom** [techfort/LokiJS#218] opened 2015-09-10 19:33 UTC
In `collection.update(obj)` doc :
> returns	| document: the document itself.

but this not occurs.

```javascript
let result = collection.update(resource);
console.log(result); // this is undefined
```

checking loki's `Collection.prototype.update` i found that the return statement is missing.

`Collection.prototype.update` should return the object like the doc says or not?

**Comment by techfort** [comment] 2015-09-10 19:35
@jpablom you're correct. This has been raised numerous times, as it was initially by design, but I'm going to address this immediately.

**Comment by techfort** [comment] 2015-09-10 19:48
@jpablom I addressed that and published it under 1.3.10. Should be available both on npm and bower. Let me know if this works for you.

**Comment by jpablom** [comment] 2015-09-10 20:24
@techfort yeah now works, thanks.
But another thing happens, when query the document immediately after update, return the object not updated, e.g.
```javascript
update: (obj) => { //{$loki: 1, meta: ..., id: 1, name: 'alex morgan'}
    const result,
        currentObj = collection.by('id', obj.id); //{$loki: 1, meta: ..., id: 1, name: 'alex'}
    if (currentObj) {
        result = collection.update(obj);
    }
    console.log(collection.by('id', obj.id)); //{$loki: 1, meta: ..., id: 1, name: 'alex'}
    return result; //{$loki: 1, meta: ..., id: 1, name: 'alex morgan'}
}
```

**Comment by techfort** [comment] 2015-09-10 20:41
@jpablom could you share a fiddle/ plunkr so i can take a look ? it looks
as if something's up with async operations but can't be sure until i look
at it.

**Comment by jpablom** [comment] 2015-09-10 21:57
Here is a [plunker](http://plnkr.co/edit/tCDAxD0K8S3ilZCFJ25D?p=preview) and i just discover what causes the issue, i use object assign to merge the updated object with the stored object in a empty object, if i remove the empty object and just merge the updated object in to the stored object works fine

**Comment by techfort** [comment] 2015-09-11 18:53
that would be the cause alright as objects are references. I'll close the issue now, let me know if you deem this to be a bug and i'll reopen.

**Closed by techfort** 2015-09-11 18:53 UTC
