### ISSUE TITLE
lokijs.org is down

### ISSUE THREAD

**Issue by yigitkonur** [techfort/LokiJS#804] opened 2019-09-08 18:49 UTC
I would like inform you about the website (lokijs.org) is down.

**Comment by IvanFon** [comment] 2019-09-10 01:37
Duplicate of: #797 

You can access the documentation at: https://rawgit.com/techfort/LokiJS/master/jsdoc/index.html

**Comment by marcellobarile** [comment] 2019-09-19 10:30
https://rawgit.com/techfort/LokiJS/master/jsdoc/index.html gives 404

**Comment by IvanFon** [comment] 2019-09-19 11:36
It’s been moved to: http://techfort.github.io/LokiJS/

**Comment by ericop** [comment] 2019-10-29 20:24
Homepage needs to be updated on https://www.npmjs.com/package/lokijs as this is what lead me to the old site today as well

**Comment by mesqueeb** [comment] 2019-11-25 01:22
I came here because I noticed the same. That new website points to the old website 😄

**Comment by muescha** [comment] 2019-11-29 23:37
### lokijs.org

yes - lokijs.org is now filled with spam nonsense content :(

this pages need an update not to point to lokijs.org:
- at https://www.npmjs.com/package/lokijs
- at http://techfort.github.io/LokiJS/


### LokiSandbox

since rawgit is stop working in near feature the LokiSandbox @ https://rawgit.com/techfort/LokiJS/master/examples/sandbox/LokiSandbox.htm should be moved to github pages

**Comment by kaeverens** [comment] 2019-12-19 14:50
https://github.com/techfort/LokiJS/wiki also points to lokijs.org

**Comment by rafalkrupinski** [comment] 2019-12-25 18:45
Might I suggest js.org free domain name? Unfortunetaly loki.js.org is taken, but lokidb is available.

Cheers

**Comment by mesqueeb** [comment] 2020-02-23 20:37
please don't close. this issue is still very relevant

**Comment by ericop** [comment] 2020-02-23 20:54
agreed, this needs work.

**Comment by mesqueeb** [comment] 2020-04-25 05:41
Oh dear!!! Issue still present

**Comment by muescha** [comment] 2020-06-26 11:46
problem still exists

/cc @techfort ?

**Closed** 2020-06-28 09:05 UTC

**Comment by finwo** [comment] 2020-06-29 11:29
Problem was only partially fixed in #842
