### ISSUE TITLE
Trailing curly bracer added to end of JSON database randomly, breaking the JSON formatting

### ISSUE THREAD

**Issue by danielleng** [techfort/LokiJS#479] opened 2016-09-25 15:18 UTC
So I have a weird problem where, from one specific database update, a curly bracer (yes, a single curly bracer) gets added to the **end** of the JSON database document (its a physical file on my hard disk), like so:
`"changes":[]}],"databaseVersion":1.1,"engineVersion":1.1,"autosave":false,"autosaveInterval":5000,"autosaveHandle":null,"options":{},"persistenceMethod":"fs","persistenceAdapter":null,"verbose":false,"events":{"init":[null],"loaded":[],"flushChanges":[],"close":[],"changes":[],"warning":[]},"ENV":"NODEJS"}}`

Notice the double '}}' at the end of the JSON doc. This then breaks subsequent database loads because the JSON is now wrongly formatted.

I have no idea how to troubleshoot this. Could anyone provide me with some tips or guidelines ? IS there a way to log ALL the changes that LokiJS makes to the physical JSON file ?

code as attached: 
[Code.txt](https://github.com/techfort/LokiJS/files/491725/Code.txt)

If you need more details, please let me know.

I have checked:
1. Ensure that all input parameters are valid.
2. Database is initialized properly.
3. All the collections are initialized and accessible. (not nulls)

Whats interesting is the **new data is inserted correctly**:
`{"type":"Claim","currency":"MYR","amount":145,"credit":false,"rate":1,"client":"Alex","total":145,"billno":"201609252252000018","paid":true,"meta":{"revision":0,"created":1474815176405,"version":0},"$loki":17}`

I observed the JSON file after every transaction, and noticed that it happens randomly with the above attached code.

**Comment by danielleng** [comment] 2016-09-25 15:21
note: i actually discovered the problem using an online JSON validator, http://www.jsoneditoronline.org/ 

And the thing itself is correctly formatted, its just the trailing curly bracer. Once its removed, I restarted my app and the database loads properly. Then it takes a few more of the same transaction above to break it again with the trailing curly bracer.

**Comment by obeliskos** [comment] 2016-09-25 15:57
Hmm that is odd...  Loki uses JSON.stringify along with only loki.serializeReplacer() which might affect the serialization.

If you can reproduce this without an adapter (memory only) and verify by calling db.serialize() to get a string to test for double curly brackets then we can isolate to loki itself.   If that always returns correctly then it may be storage adapter issue.

To help diagnose, you might try altering local copy of loki.js and change Loki.prototype.serialize to use this (to pretty print for matching braces later) : 
``javascript
    Loki.prototype.serialize = function () {
      return JSON.stringify(this, this.serializeReplacer, 2); 
    };
```

If you make that change then you might use loki sandbox and add to end of default script :
```javascript
logText(db.serialize());
```

Then try breaking it in sandbox (without saving)

**Comment by danielleng** [comment] 2016-09-26 10:56
Hi @obeliskos , 
Thanks for the response. Logging the output of db.serialize() did the trick to help identify problems.
For some reason it had something to do with running db.saveDatabase() twice in the same transaction. 

For example, this set of code is run on a single function call:
`sometable.insert(data);`
`update-some-other-table's-data-here;`
`db.saveDatabase();`
`update-another-table's-data-here;`
`db.saveDatabase();`

Changing the code above to run `saveDatabase()` only once at the end of it all, fixed the issue, and I could no longer reproduce the trailing '}'

I do not use any persistence adapters:
`"persistenceMethod":"fs","persistenceAdapter":null`

Granted, the database JSON file is stored on a local Dropbox folder that syncs with dropbox cloud all the time. Perhaps it has something to do with file system issues, or reading/writing to the same file too quickly ? Do you want me to continue troubleshooting this ? (im willing to help)

**Comment by obeliskos** [comment] 2016-09-27 11:23
Awesome, thanks for posting back with your solution.  It sounds like you are using the filesystem adapter by default... since you did not specify we detect environment and for node we use filesystem adapter.

Filesystem adapter is asynchronous (for good reason) so I guess you had two conflicting saves accessing file at once... my guess.  Not sure if that could be solved directly in the filesystem adapter's saveDatabase through some type of file locking or not but in the bigger scheme we probably don't want to have more than one save going on at once no matter what adapter you use.  This is especially relevant in autosave scenarios if save interval is less than time it takes to save.  A mutex of some kind might be a better big picture solution which puts a lock when saving and unlocks when callback from adapter is complete.  Still details to be worked out before this is actionable though.

**Comment by obeliskos** [comment] 2016-10-23 18:55
I believe this issue was resolved, thanks.  Closing

**Closed by obeliskos** 2016-10-23 18:55 UTC
