### ISSUE TITLE
Wrong results when using indices

### ISSUE THREAD

**Issue by aetna-softwares** [techfort/LokiJS#296] opened 2015-12-16 21:55 UTC
I have a case of figure in which adding an index on a collection leads to wrong result on search.

I reproduce the problem on the sandbox : 
![image](https://cloud.githubusercontent.com/assets/8860618/11854992/b71eb4fc-a447-11e5-9194-539bd76c985d.png)

![image](https://cloud.githubusercontent.com/assets/8860618/11854995/bedd5400-a447-11e5-952b-9ef725403ae3.png)

I suspect that it maybe related to the fact that the column not always have the same variable type (sometime string, sometime boolean) but I did not find mention in documentation that index should be on column with coherent type value

Here is the code used in sandbox to reproduce : 
```
// This database has already been created for you.
// var db = new loki('sandbox');

// Add a collection to the database
var coll = db.addCollection("ir.attachment", {
    unique: ['id'],
    indices: ['res_model', 'res_id', "write_date"]
});

var jsonBLOB = '[{"name":"OOR_ABC_AD01_1512_00001.pdf","res_model":"ir.attachment","AetnaMd5sum":"bd4978e05ab3b34dd844688485616b1f","AetnaSize":49864,"res_id":143,"id":144},{"name":"OOR_ABC_AD01_1512_00001.docx","res_model":"project.task","AetnaMd5sum":"abffb38135a9d82a8aec7c6c2c782aba","AetnaSize":49189,"res_id":95,"id":143},{"name":"LMA_ABC_AD01_1512_00020.pdf","res_model":"ir.attachment","AetnaMd5sum":"003460ce7634d7c38cdb2bb7063e4b6a","AetnaSize":562066,"res_id":141,"id":142},{"name":"LMA_ABC_AD01_1512_00020.pptx","res_model":"project.task","AetnaMd5sum":"be71757a7771ebc68faffb999547ada2","AetnaSize":599773,"res_id":94,"id":141},{"name":"LMA_ABC_AD01_1512_00019.pdf","res_model":"ir.attachment","AetnaMd5sum":"033702e04d0b93ac19e5894819f6ccc9","AetnaSize":562066,"res_id":139,"id":140},{"name":"LMA_ABC_AD01_1512_00019.pptx","res_model":"project.task","AetnaMd5sum":"ed4278c95beef9acb0f2da93d69e916f","AetnaSize":599773,"res_id":93,"id":139},{"name":"LLA_ADS_LC01_1512_00018.pdf","res_model":"ir.attachment","AetnaMd5sum":"bf880d2c5f0598c4177839584c95e6b9","AetnaSize":8313,"res_id":137,"id":138},{"name":"LLA_ADS_LC01_1512_00018.docx","res_model":"project.task","AetnaMd5sum":"68db1cfb030f189b8e84eb5fc2b7bb51","AetnaSize":10404,"res_id":92,"id":137},{"name":"LMA_ABC_AD01_1512_00017.pdf","res_model":"ir.attachment","AetnaMd5sum":"601becfab859e1cf2d68ac66d7e164e3","AetnaSize":392450,"res_id":135,"id":136},{"name":"LMA_ABC_AD01_1512_00017.docx","res_model":"project.task","AetnaMd5sum":"aa9a95883c6f8f892042af86cf9c9997","AetnaSize":285650,"res_id":91,"id":135},{"name":"LMA_ADS_LC01_1512_00016.pdf","res_model":"ir.attachment","AetnaMd5sum":"05c6126791e82f13bbb6b1265d8402ad","AetnaSize":63851,"res_id":133,"id":134},{"name":"LMA_ADS_LC01_1512_00016","res_model":"project.task","AetnaMd5sum":"bbbaa2ac3c784a2f297474620df6bfb8","AetnaSize":55782,"res_id":90,"id":133},{"name":"LMA_ADS_LC01_1512_00015.pdf","res_model":"ir.attachment","AetnaMd5sum":"0f657016b14c2323708e4c19291c7681","AetnaSize":18117,"res_id":131,"id":132},{"name":"LMA_ADS_LC01_1512_00015","res_model":"project.task","AetnaMd5sum":"665c7569d524b5f0b703e9667514c491","AetnaSize":4619,"res_id":89,"id":131},{"name":"LMA_ABC_AD01_1512_00014.pdf","res_model":"ir.attachment","AetnaMd5sum":"a3534013609a66266dfa8cd7ddf4d88b","AetnaSize":92333,"res_id":129,"id":130},{"name":"LMA_ABC_AD01_1512_00014.docx","res_model":"project.task","AetnaMd5sum":"b4be420af0fcfbd67cab895fd3de626d","AetnaSize":142186,"res_id":88,"id":129},{"name":"LMA_ABC_AD01_1512_00013.pdf","res_model":"ir.attachment","AetnaMd5sum":"9298e7293f52d9975d7b2d0eee90f6d0","AetnaSize":91217,"res_id":127,"id":128},{"name":"LMA_ABC_AD01_1512_00013.docx","res_model":"project.task","AetnaMd5sum":"ab25fdd8191d53d2b0d2f8a85a9f97be","AetnaSize":346589,"res_id":87,"id":127},{"name":"OOR_ABC_AD01_1512_00012.pdf","res_model":"ir.attachment","AetnaMd5sum":"b0b81d4aabef57376f05e1e50d35cc52","AetnaSize":61123,"res_id":125,"id":126},{"name":"OOR_ABC_AD01_1512_00012.xlsx","res_model":"project.task","AetnaMd5sum":"1f97876f0f3f52f7622939c820e9e1da","AetnaSize":41991,"res_id":86,"id":125},{"name":"OOR_ADS_LC01_1512_00011.pdf","res_model":"ir.attachment","AetnaMd5sum":"4fae4c93b944aa30ecae2ba5bb058318","AetnaSize":405657,"res_id":123,"id":124},{"name":"OOR_ADS_LC01_1512_00011.docx","res_model":"project.task","AetnaMd5sum":"8c10d2cff4f3109e7f57ad9ad87d9c25","AetnaSize":260464,"res_id":85,"id":123},{"name":"OOR_ADS_LC01_1512_00010.pdf","res_model":"ir.attachment","AetnaMd5sum":"c55d3a7fe36ec591be6654f1e3007246","AetnaSize":391975,"res_id":121,"id":122},{"name":"OOR_ADS_LC01_1512_00010.docx","res_model":"project.task","AetnaMd5sum":"0e3566c38b641958bca082178fc5cc3e","AetnaSize":238725,"res_id":84,"id":121},{"name":"OOR_ABC_AD01_1512_00009.pdf","res_model":"ir.attachment","AetnaMd5sum":"dbd738a6e524f233f4f52cfdaf62145b","AetnaSize":521318,"res_id":119,"id":120},{"name":"OOR_ABC_AD01_1512_00009.docx","res_model":"project.task","AetnaMd5sum":"2502a2a39ac865e67efc2494123e4d9a","AetnaSize":1210714,"res_id":83,"id":119},{"name":"OOR_ADS_LC01_1512_00008.pdf","res_model":"ir.attachment","AetnaMd5sum":"2ef5792d2d53784105cd7dae4cb4b4e3","AetnaSize":562262,"res_id":117,"id":118},{"name":"OOR_ADS_LC01_1512_00008.pptx","res_model":"project.task","AetnaMd5sum":"5550c5c9fa99a1e06176439d19e27682","AetnaSize":153384,"res_id":82,"id":117},{"name":"OOR_ABC_AD01_1512_00007.pdf","res_model":"ir.attachment","AetnaMd5sum":"3b5637b746a3e299daff7b974b7a7f6f","AetnaSize":91111,"res_id":115,"id":116},{"name":"OOR_ABC_AD01_1512_00007.docx","res_model":"project.task","AetnaMd5sum":"d20173f64915417bd946c51e9747e174","AetnaSize":346589,"res_id":81,"id":115},{"name":"test_xls.xlsx","res_model":"document.aetna.template","AetnaMd5sum":false,"AetnaSize":0,"res_id":11,"id":112},{"name":"test_props.docx","res_model":"document.aetna.template","AetnaMd5sum":false,"AetnaSize":0,"res_id":3,"id":111},{"name":"AA00S000N0230.docx","res_model":"document.aetna.template","AetnaMd5sum":false,"AetnaSize":0,"res_id":10,"id":110},{"name":"AA00S000N0090.docx","res_model":"document.aetna.template","AetnaMd5sum":false,"AetnaSize":0,"res_id":9,"id":109},{"name":"AA00S000N0080.docx","res_model":"document.aetna.template","AetnaMd5sum":false,"AetnaSize":0,"res_id":8,"id":108},{"name":"test_ppt.pptx","res_model":"document.aetna.template","AetnaMd5sum":false,"AetnaSize":0,"res_id":5,"id":107},{"name":"AA00S000N0030.docx","res_model":"document.aetna.template","AetnaMd5sum":false,"AetnaSize":0,"res_id":7,"id":106},{"name":"OOR__AD01_1512_00002.pdf","res_model":"ir.attachment","AetnaMd5sum":"637343f0ed4cb5ec7a958dfeb40e85de","AetnaSize":9252,"res_id":104,"id":105},{"name":"OOR__AD01_1512_00002.docx","res_model":"project.task","AetnaMd5sum":"982d6f2637891ca286a83f02228d4bc2","AetnaSize":47791,"res_id":76,"id":104},{"name":"OOR__AD01_1512_00001.pdf","res_model":"ir.attachment","AetnaMd5sum":"b4f9b4eff2beb91861a3392c8f2ccbde","AetnaSize":9252,"res_id":102,"id":103},{"name":"OOR__AD01_1512_00001.docx","res_model":"project.task","AetnaMd5sum":"281c2934cff7a9c56acfd17c8c9aa5c2","AetnaSize":11483,"res_id":75,"id":102},{"name":"/web/js/web.assets_backend/007d2e0","res_model":false,"AetnaMd5sum":false,"AetnaSize":0,"res_id":0,"id":97},{"name":"/web/css/web.assets_backend/007d2e0","res_model":false,"AetnaMd5sum":false,"AetnaSize":0,"res_id":0,"id":96},{"name":"reponse_appel_offre.docx","res_model":"document.aetna.template","AetnaMd5sum":false,"AetnaSize":0,"res_id":4,"id":46},{"name":"/web/js/web.assets_common/ceba8ad","res_model":false,"AetnaMd5sum":false,"AetnaSize":0,"res_id":0,"id":5},{"name":"/web/css/web.assets_common/ceba8ad","res_model":false,"AetnaMd5sum":false,"AetnaSize":0,"res_id":0,"id":3}]'

var allItems = JSON.parse(jsonBLOB) ;

coll.insert(allItems) ;

var results = coll.find({res_model: 'project.task' }) ;
var resultsNoLoki = allItems.filter(function(item){ 
    return item.res_model === 'project.task' ; 
}) ;

logText(results.length+ " VS "+resultsNoLoki.length)
logObject(results);

// This statement sends to Inspector
inspectObject(db);
```

**Comment by obeliskos** [comment] 2015-12-16 23:56
Thanks for the very detailed repro test case.  You were correct in thinking that mixing Boolean and strings might have been causing the issue.  I modified our ltHelper and gtHelper functions to handle the case where a boolean is involved in the comparison.  In javascript true < 'hello' is false, but true > 'hello' is also false, so I do strict checking now to enforce edge case where Boolean is mixed in with strings.  

Let me know if you have any issues as the change has been checked into main branch.  Your sandbox looks pretty old as well, you might want to grab the latest of that or ensure your browser is not caching old sandbox (if pointing to live rawgit url).

I believe @KimSchneider originally added our ltHelper and gtHelper functions (or added null checking?).  This will hopefully serve to notify him I have modified those functions in case he cares to review.

**Comment by KimSchneider** [comment] 2015-12-17 08:25
I can't remember doing this :) Just one question: Is checking for null and undefined in seperate if conditions faster than checking with == null or both checks in one condition?

**Comment by obeliskos** [comment] 2015-12-17 11:37
Oh, well thanks for the suggestion.  I did that and it's difficult to say for sure but it looks like it may help a bit.   Hard to guess jit optimizer, but combined checks are the end goal so if anything it will help to ensure that.

**Comment by aetna-softwares** [comment] 2015-12-17 23:01
I checked with the rawgit sandbox and the correction works well (please note that the sandbox link on http://lokijs.org/#/demo point to the old version).

I am using loki with npm/browserify. Is it possible to publish a new npm release with the bugfix ?

About the remark of @KimSchneider for "== null" VS "=== null || === undefined", I found a jsperf about it : 
http://jsperf.com/equals-null-or-undefined

The test gives barely no difference on FF. On Chrome, "== null" is slightly faster.

**Comment by obeliskos** [comment] 2015-12-17 23:45
Great.  Yes we moved sandbox into lokijs repository (link on main lokijs github page). 

Let's see if @techfort can do an npm push sometime soon (and also to possibly fix that link).

**Comment by KimSchneider** [comment] 2015-12-18 08:29
I took a second thought on this and the current or-solution is the best. WIth == the system performes a type conversion, which should end up being slower all of the time.

**Comment by aetna-softwares** [comment] 2016-02-11 20:27
Hi again

I came across a similar bug when mixing number and string.
![image](https://cloud.githubusercontent.com/assets/8860618/12989466/049a3fc2-d106-11e5-885e-242c80b3f76f.png)

here is the new test code (just add change one record with a number value)
```
var db = new loki('sandbox.db');

var coll = db.addCollection("ir.attachment", {
    unique: ['id'],
    indices: ['res_model', 'res_id', "write_date"]
});

var jsonBLOB = '[{"name":"OOR_ABC_AD01_1512_00001.pdf","res_model":12,"AetnaMd5sum":"bd4978e05ab3b34dd844688485616b1f","AetnaSize":49864,"res_id":143,"id":144},{"name":"OOR_ABC_AD01_1512_00001.docx","res_model":"project.task","AetnaMd5sum":"abffb38135a9d82a8aec7c6c2c782aba","AetnaSize":49189,"res_id":95,"id":143},{"name":"LMA_ABC_AD01_1512_00020.pdf","res_model":"ir.attachment","AetnaMd5sum":"003460ce7634d7c38cdb2bb7063e4b6a","AetnaSize":562066,"res_id":141,"id":142},{"name":"LMA_ABC_AD01_1512_00020.pptx","res_model":"project.task","AetnaMd5sum":"be71757a7771ebc68faffb999547ada2","AetnaSize":599773,"res_id":94,"id":141},{"name":"LMA_ABC_AD01_1512_00019.pdf","res_model":"ir.attachment","AetnaMd5sum":"033702e04d0b93ac19e5894819f6ccc9","AetnaSize":562066,"res_id":139,"id":140},{"name":"LMA_ABC_AD01_1512_00019.pptx","res_model":"project.task","AetnaMd5sum":"ed4278c95beef9acb0f2da93d69e916f","AetnaSize":599773,"res_id":93,"id":139},{"name":"LLA_ADS_LC01_1512_00018.pdf","res_model":"ir.attachment","AetnaMd5sum":"bf880d2c5f0598c4177839584c95e6b9","AetnaSize":8313,"res_id":137,"id":138},{"name":"LLA_ADS_LC01_1512_00018.docx","res_model":"project.task","AetnaMd5sum":"68db1cfb030f189b8e84eb5fc2b7bb51","AetnaSize":10404,"res_id":92,"id":137},{"name":"LMA_ABC_AD01_1512_00017.pdf","res_model":"ir.attachment","AetnaMd5sum":"601becfab859e1cf2d68ac66d7e164e3","AetnaSize":392450,"res_id":135,"id":136},{"name":"LMA_ABC_AD01_1512_00017.docx","res_model":"project.task","AetnaMd5sum":"aa9a95883c6f8f892042af86cf9c9997","AetnaSize":285650,"res_id":91,"id":135},{"name":"LMA_ADS_LC01_1512_00016.pdf","res_model":"ir.attachment","AetnaMd5sum":"05c6126791e82f13bbb6b1265d8402ad","AetnaSize":63851,"res_id":133,"id":134},{"name":"LMA_ADS_LC01_1512_00016","res_model":"project.task","AetnaMd5sum":"bbbaa2ac3c784a2f297474620df6bfb8","AetnaSize":55782,"res_id":90,"id":133},{"name":"LMA_ADS_LC01_1512_00015.pdf","res_model":"ir.attachment","AetnaMd5sum":"0f657016b14c2323708e4c19291c7681","AetnaSize":18117,"res_id":131,"id":132},{"name":"LMA_ADS_LC01_1512_00015","res_model":"project.task","AetnaMd5sum":"665c7569d524b5f0b703e9667514c491","AetnaSize":4619,"res_id":89,"id":131},{"name":"LMA_ABC_AD01_1512_00014.pdf","res_model":"ir.attachment","AetnaMd5sum":"a3534013609a66266dfa8cd7ddf4d88b","AetnaSize":92333,"res_id":129,"id":130},{"name":"LMA_ABC_AD01_1512_00014.docx","res_model":"project.task","AetnaMd5sum":"b4be420af0fcfbd67cab895fd3de626d","AetnaSize":142186,"res_id":88,"id":129},{"name":"LMA_ABC_AD01_1512_00013.pdf","res_model":"ir.attachment","AetnaMd5sum":"9298e7293f52d9975d7b2d0eee90f6d0","AetnaSize":91217,"res_id":127,"id":128},{"name":"LMA_ABC_AD01_1512_00013.docx","res_model":"project.task","AetnaMd5sum":"ab25fdd8191d53d2b0d2f8a85a9f97be","AetnaSize":346589,"res_id":87,"id":127},{"name":"OOR_ABC_AD01_1512_00012.pdf","res_model":"ir.attachment","AetnaMd5sum":"b0b81d4aabef57376f05e1e50d35cc52","AetnaSize":61123,"res_id":125,"id":126},{"name":"OOR_ABC_AD01_1512_00012.xlsx","res_model":"project.task","AetnaMd5sum":"1f97876f0f3f52f7622939c820e9e1da","AetnaSize":41991,"res_id":86,"id":125},{"name":"OOR_ADS_LC01_1512_00011.pdf","res_model":"ir.attachment","AetnaMd5sum":"4fae4c93b944aa30ecae2ba5bb058318","AetnaSize":405657,"res_id":123,"id":124},{"name":"OOR_ADS_LC01_1512_00011.docx","res_model":"project.task","AetnaMd5sum":"8c10d2cff4f3109e7f57ad9ad87d9c25","AetnaSize":260464,"res_id":85,"id":123},{"name":"OOR_ADS_LC01_1512_00010.pdf","res_model":"ir.attachment","AetnaMd5sum":"c55d3a7fe36ec591be6654f1e3007246","AetnaSize":391975,"res_id":121,"id":122},{"name":"OOR_ADS_LC01_1512_00010.docx","res_model":"project.task","AetnaMd5sum":"0e3566c38b641958bca082178fc5cc3e","AetnaSize":238725,"res_id":84,"id":121},{"name":"OOR_ABC_AD01_1512_00009.pdf","res_model":"ir.attachment","AetnaMd5sum":"dbd738a6e524f233f4f52cfdaf62145b","AetnaSize":521318,"res_id":119,"id":120},{"name":"OOR_ABC_AD01_1512_00009.docx","res_model":"project.task","AetnaMd5sum":"2502a2a39ac865e67efc2494123e4d9a","AetnaSize":1210714,"res_id":83,"id":119},{"name":"OOR_ADS_LC01_1512_00008.pdf","res_model":"ir.attachment","AetnaMd5sum":"2ef5792d2d53784105cd7dae4cb4b4e3","AetnaSize":562262,"res_id":117,"id":118},{"name":"OOR_ADS_LC01_1512_00008.pptx","res_model":"project.task","AetnaMd5sum":"5550c5c9fa99a1e06176439d19e27682","AetnaSize":153384,"res_id":82,"id":117},{"name":"OOR_ABC_AD01_1512_00007.pdf","res_model":"ir.attachment","AetnaMd5sum":"3b5637b746a3e299daff7b974b7a7f6f","AetnaSize":91111,"res_id":115,"id":116},{"name":"OOR_ABC_AD01_1512_00007.docx","res_model":"project.task","AetnaMd5sum":"d20173f64915417bd946c51e9747e174","AetnaSize":346589,"res_id":81,"id":115},{"name":"test_xls.xlsx","res_model":"document.aetna.template","AetnaMd5sum":false,"AetnaSize":0,"res_id":11,"id":112},{"name":"test_props.docx","res_model":"document.aetna.template","AetnaMd5sum":false,"AetnaSize":0,"res_id":3,"id":111},{"name":"AA00S000N0230.docx","res_model":"document.aetna.template","AetnaMd5sum":false,"AetnaSize":0,"res_id":10,"id":110},{"name":"AA00S000N0090.docx","res_model":"document.aetna.template","AetnaMd5sum":false,"AetnaSize":0,"res_id":9,"id":109},{"name":"AA00S000N0080.docx","res_model":"document.aetna.template","AetnaMd5sum":false,"AetnaSize":0,"res_id":8,"id":108},{"name":"test_ppt.pptx","res_model":"document.aetna.template","AetnaMd5sum":false,"AetnaSize":0,"res_id":5,"id":107},{"name":"AA00S000N0030.docx","res_model":"document.aetna.template","AetnaMd5sum":false,"AetnaSize":0,"res_id":7,"id":106},{"name":"OOR__AD01_1512_00002.pdf","res_model":"ir.attachment","AetnaMd5sum":"637343f0ed4cb5ec7a958dfeb40e85de","AetnaSize":9252,"res_id":104,"id":105},{"name":"OOR__AD01_1512_00002.docx","res_model":"project.task","AetnaMd5sum":"982d6f2637891ca286a83f02228d4bc2","AetnaSize":47791,"res_id":76,"id":104},{"name":"OOR__AD01_1512_00001.pdf","res_model":"ir.attachment","AetnaMd5sum":"b4f9b4eff2beb91861a3392c8f2ccbde","AetnaSize":9252,"res_id":102,"id":103},{"name":"OOR__AD01_1512_00001.docx","res_model":"project.task","AetnaMd5sum":"281c2934cff7a9c56acfd17c8c9aa5c2","AetnaSize":11483,"res_id":75,"id":102},{"name":"/web/js/web.assets_backend/007d2e0","res_model":false,"AetnaMd5sum":false,"AetnaSize":0,"res_id":0,"id":97},{"name":"/web/css/web.assets_backend/007d2e0","res_model":false,"AetnaMd5sum":false,"AetnaSize":0,"res_id":0,"id":96},{"name":"reponse_appel_offre.docx","res_model":"document.aetna.template","AetnaMd5sum":false,"AetnaSize":0,"res_id":4,"id":46},{"name":"/web/js/web.assets_common/ceba8ad","res_model":false,"AetnaMd5sum":false,"AetnaSize":0,"res_id":0,"id":5},{"name":"/web/css/web.assets_common/ceba8ad","res_model":false,"AetnaMd5sum":false,"AetnaSize":0,"res_id":0,"id":3}]'

var allItems = JSON.parse(jsonBLOB) ;

coll.insert(allItems) ;

var results = coll.find({res_model: 'project.task' }) ;
var resultsNoLoki = allItems.filter(function(item){ 
    return item.res_model === 'project.task' ; 
}) ;

logText(results.length+ " VS "+resultsNoLoki.length)
logObject(results);

// This statement sends to Inspector
inspectObject(db);
```

**Comment by aetna-softwares** [comment] 2016-03-31 09:48
Hi,

@obeliskos, did you have the time to check the case I submited ?

**Comment by obeliskos** [comment] 2016-03-31 10:42
I don't remember... but we have made fixes to our comparison helper functions since you reported this.

When I run your last test code on loki sandbox I get 17 vs 17, so this possibly is not applicable anymore?

[Loki Sandbox Link](https://rawgit.com/techfort/LokiJS/master/examples/sandbox/LokiSandbox.htm)

**Comment by aetna-softwares** [comment] 2016-03-31 11:31
I just test again in the sandbox and it still give me 6 VS 17

**Comment by Kanaye** [comment] 2016-03-31 12:13
Hey all :smile:!
I tested this with the code above and it looks like this issue only appears in chrome :worried:.
I tested in firefox (dev-edition and stable) and  ms edge and I get ``17 VS 17``.
But in chrome stable and canary I get ``6 VS 17``.
All browsers are running on windows 10 stable.
I hope that helps :smile:.

**Comment by obeliskos** [comment] 2016-03-31 20:41
Thanks @Kanaye, I am able to reproduce this error in Chrome.  I will look into this.

**Comment by obeliskos** [comment] 2016-03-31 22:03
Alright, I believe I have found the problem.  Seems our handling of mixed types was bad on all browsers probably just a different sort algorithm used on chrome.

This should be fixed now... @aetna-softwares and @Kanaye feel free to try out and post results.

**Comment by aetna-softwares** [comment] 2016-04-01 07:11
works for me :)

**Comment by Kanaye** [comment] 2016-04-01 15:48
Also works for me :)
Thanks for fixing this :+1:.
I think you can close this issue now.

**Comment by techfort** [comment] 2016-04-01 16:26
@aetna-softwares @Kanaye @obeliskos closing this, thanks for working on it.

**Closed by techfort** 2016-04-01 16:26 UTC
