### ISSUE TITLE
How to use the update() function for a collection?

### ISSUE THREAD

**Issue by bizMD** [techfort/LokiJS#215] opened 2015-09-06 07:10 UTC
Sorry if this seems like a basic question.

I'm trying to figure out how to use the update() function because it's stated in the docs that it takes only one argument, the object to be updated itself -- http://lokijs.org/#/docs#update

After the object is passed in, it returns the document. Now I assume that adding updates to the returned object will automatically reflect in the collection?

I know we're using Mongo-inspired functions, but in Mongo, the update() function has three arguments. Is there something missing in the docs or is this really the way to do updates in Loki?

```
collection.update({GetGeoIPResult: {IP: '112.30.62.255'}}) = '0.0.0.0'
```

EDIT:
I saw in slide 6 here (http://www.slideshare.net/techfort/lokijs) that updates are optional, and we only do this to force a re-indexing of the collections.

How do I know Loki will update the documents I need in the following use case?

> I poll a database every time interval for some data
> The data that is returned to me is last modified a certain number of minutes ago
> I save the results in my collection, inserting new data and replacing old ones

How does Loki know I want to replace a document with a more up to date one?

**Comment by techfort** [comment] 2015-09-06 07:59
Hi @bizMD : the update() function works differently from the Mongo one. At the moment, you modify an object and pass it to the update() function, however the object is not returned, only the object in the collection is modified. This is in the majority of cases good enough, as the object you pass is a reference to the object in the collection. 
If you are using clones, you need to retrieve the object again to make sure to be using the correct object.

On a side note: I want to change this behaviour to work more like MongoDB, but as `update()` is such a vital operation, this would cause major backward incompatibility, so it would cause a major version release (eg. v2.0)
It is possible we will in fact apply this change and release a v2.0 along with some other major changes.
As this is not a bug i'll close the issue, drop me a mail if you still need help with this.

**Closed by techfort** 2015-09-06 07:59 UTC
