### ISSUE TITLE
db save circular structure issue

### ISSUE THREAD

**Issue by teef** [techfort/LokiJS#60] opened 2015-01-13 11:29 UTC
Currently I have a problem in the area of loading/saving database. After object update and try to save db the following error occurs:
```javascript
stream.js:94
      throw er; // Unhandled stream error in pipe.
            ^
TypeError: Converting circular structure to JSON
    at Object.stringify (native)
    at LokiEventEmitter.Loki.serialize (/home/teef/leonardo/WebApplications/Leonardo-CommHub/node_modules/lokijs/src/lokijs.js:385:19)
    at LokiEventEmitter.Loki.saveDatabase (/home/teef/leonardo/WebApplications/Leonardo-CommHub/node_modules/lokijs/src/lokijs.js:744:47)
```
I am using one collection as well as one dynamic view.

Seems like there are two dynamic views which should not happen.

```javascript
DynamicViews: 
   [ { collection: [Circular],
       name: 'aciveDevices',
       persistent: false,
       resultset: [Object],
       resultdata: [],
       resultsdirty: true,
       cachedresultset: null,
       filterPipeline: [],
       sortFunction: null,
       sortCriteria: null,
       sortDirty: false,
       events: [Object] },
     { collection: [Circular],
       name: 'aciveDevices',
       persistent: false,
       resultset: [Object],
       resultdata: [],
       resultsdirty: false,
       cachedresultset: null,
       filterPipeline: [Object],
       sortFunction: null,
       sortCriteria: null,
       sortDirty: false,
       events: [Object] } ],
```

Database: https://gist.github.com/teef/c3f8f2139a1e13188e09

**Comment by obeliskos** [comment] 2015-01-14 00:10
I have tried to reproduce your error but so far I have not been able to.   There are two areas of specific relevance to the problem you describe which are : 
- when serializing resultsets and dynamicviews we are overriding the toJSON to clear out the collection... so the end serialized string should be null for collections so it will not create the error you describe.  when we load (in loadJSON) we reattach the collection references
- your database gist shows you are using a where filter which is not serializable (a function is not serialiable).  loki should be clearing out any where filters during load (we will call rematerialize on dynamic views to do that).  If at all possible you should use find filters which are serialized correctly.  If you use where filters you will need to reattach (reapply) those filters after database is reloaded.

So what I have so far is mostly done in my browser sandbox which you can view here (sorry the code isn't very pretty but its just a test) : 
http://www.obeliskos.com/TridentSandbox/SilentSandbox.htm#RunApp=serializeTest

I do a loadJSON with the data from your gist; I update an object, i create my own dynamic view with a where clause, serialize out to a string, create and load a second database from that string, and view results I see the difference between original view results and rematerialized view (with where clauses removed).

You should also be able to inspect the original database and reloaded databases to observe the dynamic views have no duplication or errors raised during serialization.

**Comment by teef** [comment] 2015-01-14 19:54
Hello,
Thanks for explanation. I will analyze your results tomorrow. From I have
seen your are using findOne() method. I couldn't find it in documentation.
Is it function from current release or something upcoming?

2015-01-14 1:10 GMT+01:00 obeliskos <notifications@github.com>:

> I have tried to reproduce your error but so far I have not been able to.
> There are two areas of specific relevance to the problem you describe which
> are :
>
>    - when serializing resultsets and dynamicviews we are overriding the
>    toJSON to clear out the collection... so the end serialized string should
>    be null for collections so it will not create the error you describe. when
>    we load (in loadJSON) we reattach the collection references
>    - your database gist shows you are using a where filter which is not
>    serializable (a function is not serialiable). loki should be clearing out
>    any where filters during load (we will call rematerialize on dynamic views
>    to do that). If at all possible you should use find filters which are
>    serialized correctly. If you use where filters you will need to reattach
>    (reapply) those filters after database is reloaded.
>
> So what I have so far is mostly done in my browser sandbox which you can
> view here (sorry the code isn't very pretty but its just a test) :
>
> http://www.obeliskos.com/TridentSandbox/SilentSandbox.htm#RunApp=serializeTest
>
> I do a loadJSON with the data from your gist; I update an object, i create
> my own dynamic view with a where clause, serialize out to a string, create
> and load a second database from that string, and view results I see the
> difference between original view results and rematerialized view (with
> where clauses removed).
>
> You should also be able to inspect the original database and reloaded
> databases to observe the dynamic views have no duplication or errors raised
> during serialization.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/techfort/LokiJS/issues/60#issuecomment-69847195>.
>



-- 
Tomasz Fidecki

**Comment by obeliskos** [comment] 2015-01-15 02:10
I converted the example to run under node and it seems to work the same as my browser sample (no errors and serialized database has no duplicate dynamic views and the collection references are null).  I tried db.serialize() and loadJSON() and also db.saveDatabase()/db.loadDatabase() both behaved as expected.  

findOne() has actually always been there as long as I have used loki.  That was one of the mongo api functions Techfort originally implemented and we have kept it.  Must have slipped through the documentation.  Basically just returns a single object if found (instead of array which find returns).

How old is the version of loki that you are using? Is it the latest?  NPM is up to 1.1.14.

**Comment by teef** [comment] 2015-01-16 04:04
Currently I am using 1.1.11
According to a given advice I am changing the code to use find filters.
During DB loading tests I found out that scenario when I am loading DB without having file created ends up with:
```
{ [Error: ENOENT, open 'commhub-devices.json'] errno: 34, code: 'ENOENT', path: 'commhub-devices.json' }
```
Is it by design? Or the new file should be created? Is there a place I could configure this?

**Comment by dnfpili** [comment] 2015-01-16 10:52
Hmmm, somehow this same error happens to me whenever I try to manually call saveDatabase() when I have autosave set to true during initialization.

**Comment by obeliskos** [comment] 2015-01-16 12:02
My example was just to try to recreate the error which it did not do, so don't try to pattern after it too much.

Sounds like (from you and Dan) that long term I need to create a matrix of tests around autoload, autosave using all three persistence methods (as well as environment detection).

But for now, can you describe exactly what database initialization options you are using?  What is the line where you create new loki(...)?

If you are utilizing autoload, for now you should pass in your own autoloadCallback option which you should be able to use to handle the empty database error (either by ignoring or doing database initialization yourself).  In the future I might change it so that it does not raise an error if autoloading a database that doesn't exist yet.

So please give me constructor information like (for example) : 
```javascript
var db = new loki('test', 
	{ 
    	autosave: true, 
        autoload: true,
        persistenceMethod: 'adapter',
        adapter: new lokiIndexedAdapter('indexedTest'),
        autoloadCallback: dbInit
	});
```
Since you are using node your's will look different, so just post what you are currently using when you get the error.

**Comment by obeliskos** [comment] 2015-01-16 12:27
I have also noticed a bug in the loki contructor where : 

``` javascript
this.ENV = options ? (options.env || 'NODEJS') : getENV();
```
should likely be : 
``` javascript
this.ENV = options ? (options.persistenceMethod || 'NODEJS') : getENV();
```
That may not matter if you are using node but it messes up local storage and indexeddb.  As I do more thorough testing across multiple configurations over the next day or so, I will post that fix that as well.

**Comment by dnfpili** [comment] 2015-01-16 12:46
Sorry about that, here is what I was using,

```javascript

var loki = require("lokijs")
var db = new loki("test3", {
            autosave : true,
            autosaveInterval : 1000
});

db.addCollection("folders");
console.log(db.listCollections());
db.saveDatabase();

```

And here is the one I'm using when I want to load an existing database. 

```javascript

var loki = require("lokijs")
        var db = new loki("test4", {
            autosave : true,
            autosaveInterval : 1000
        });

db.loadDatabase({}, function(){

            var folders = db.addCollection("folders");
            folders.insert({name: "sample"});

            db.saveDatabase();
});

````

Both of them ends up with
````
Uncaught node.js Error 

TypeError: Converting circular structure to JSON
    at Object.stringify (native)
    at LokiEventEmitter.Loki.serialize (X:\nginx146\html\spark-desktop\node_modules\lokijs\src\lokijs.js:385:19)
    at LokiEventEmitter.Loki.saveDatabase (X:\nginx146\html\spark-desktop\node_modules\lokijs\src\lokijs.js:744:47)
    at file:///X:/nginx146/html/spark-desktop/test3.html:40:16
    at readFileCallback (X:\nginx146\html\spark-desktop\node_modules\lokijs\src\lokijs.js:678:11)
    at fs.js:289:14
    at Object.oncomplete (fs.js:97:15)
````

I also noticed that whenever I add a collection and not insert any data, loki does not save it even when autosave is on, thus I had to call the saveDatabase() manually somewhere in my code and stumbled upon this.

Not sure if I was doing something wrong. Please enlighten me. :)

Dan

**Comment by techfort** [comment] 2015-01-16 12:49
Hi Tomasz, could you try updating to the latest version (should be 1.1.14)
and check if the problem is still there?

**Comment by teef** [comment] 2015-01-16 18:18
Upgraded to 1.1.14.
My db constructor is as follows:
```javascript
this.db = new this.loki('commhub-devices.json',
  {
    autosave: true,
    autosaveInterval: 1000 * 60 * 10,
    autoload: true,
    autoloadCallback : this._dbLoadHandler,
  });
```
It is called within other object constructor.
Then this happens:
```javascript
this.db.loadDatabase({}, function(err, data) {
          ^
TypeError: Cannot call method 'loadDatabase' of undefined
    at CommHubRPCServer._dbLoadHandler (/home/teef/leonardo/WebApplications/Leonardo-CommHub/commhub-rpc-server.js:124:11)
    at readFileCallback (/home/teef/leonardo/WebApplications/Leonardo-CommHub/node_modules/lokijs/src/lokijs.js:673:20)
    at fs.js:207:20
    at Object.oncomplete (fs.js:107:15)
```
It seems that this.db is undefined while processing this._dbLoadHandler invoked by autoloadCallback feature.
I have temporarily suppressed this by disabling autoloadCallback and calling this._dbLoadHandler manually. But then I have issues with non-exisitng or empty file or file with '{}' only.

**Comment by teef** [comment] 2015-01-17 06:49
Hi,
To ease the analysis I have created a gist with:
* database creation
* collection and dynamic view creation
* inserting 2 objects
* database saving

the outcome is:
```javascript
DB dynamic view
[ { deviceType: 'dimmer',
    deviceName: 'Dimmer',
    logicalAddr: 254,
    serialNumber: [ 54, 52, 16, 20, 0, 8, 0 ],
    serialNumberStr: '54521620000800',
    active: true,
    meta: { revision: 0, created: 0, version: 0 },
    '$loki': 1 } ]

/home/teef/leonardo/WebApplications/Leonardo-CommHub/node_modules/lokijs/src/lokijs.js:383
      return JSON.stringify(this);
                  ^
TypeError: Converting circular structure to JSON
    at Object.stringify (native)
    at LokiEventEmitter.Loki.serialize (/home/teef/leonardo/WebApplications/Leonardo-CommHub/node_modules/lokijs/src/lokijs.js:383:19)
    at LokiEventEmitter.Loki.saveDatabase (/home/teef/leonardo/WebApplications/Leonardo-CommHub/node_modules/lokijs/src/lokijs.js:742:47)
```

**Comment by obeliskos** [comment] 2015-01-17 19:43
I am able to reproduce this error now, thanks.  

I believe the issue is related to keeping a reference to the file stream within the database itself.  I think the serialization is failing due to it trying to serialize the file system object which is attached to the db.

I don't know why we would need to do this but this may be more in Techfort's area of expertise so i will research a little more and pass results on to him.   He has been offline for a few days, so once he gets back on I'm sure he will be more actively involved in this issue.

**Comment by obeliskos** [comment] 2015-01-18 01:33
After further testing it does not appear to be the issue I described in the previous post.

It looks like node setInterval return value is not a 'handle' but an intervalObject that has circular references.  So I may need to research their setInterval implementation further.

If you want to circumvent the problem short term, you could change loki.js serialize function to be :  
```javascript
    Loki.prototype.serialize = function () {
      var ash = this.autosaveHandle;
      this.autosaveHandle = null;
      return JSON.stringify(this);
      this.autosaveHandle = ash;
    };
```
Also of note is that since we are leaving the interval timer running, to end the program I had to call : 
```javascript
process.exit(code=0);
```

**Comment by obeliskos** [comment] 2015-01-18 14:20
I have submitted a fix which should hopefully fix your issue.  Feel free to try it out and let me know of your results.  

In order to help us more granularly control what is being serialized along with the database, I am implementing a JSON.stringify mode utilizing a serialReplacer function to allow us to null out any top level (loki/db) properties which do not need to be serialized. 

You should not need to modify your code as this error was internal bug (which is also specific to nodejs implementation of setInterval).

I did do minor tweak to environment detection to fix browser detection, but that should not affect you... your sample is still being detected as NODEJS when I run under node.

**Comment by dnfpili** [comment] 2015-01-19 13:40
I tried it out from the latest source and it seems to have been fixed in my case.
I also noticed that it now autosaves the database too when I add an empty collection.

Thank you very much!

**Comment by techfort** [comment] 2015-01-19 13:49
Thanks @obeliskos ! Back from holiday today, we'll wait for @teef's confirmation that the issue is fixed before we close. As soon as i get that i'll publish it on npm as this seems to be a pretty nasty issue.

**Comment by obeliskos** [comment] 2015-01-19 23:36
Glad its working good for you, Dan.

I had assumed that the db reference would be kept globally, outside the context of a 'this' reference, so the autoloadCallback would not need a reference to the database.  In theory we could pass db reference along with 'err' and 'data'.  Any opinions (from anyone) on whether this should be done?

**Comment by teef** [comment] 2015-01-20 05:05
Hello Loki Team,
I have tested quite a few scenarios around database (creation, insertion, creation of dynamic views, applying find and where filters) and it seems that circular issue is gone. Good job done. Thanks.

One question regarding database loading. When the database file does not exists load function returns  with err=34 for Node. Currently before loading I am checking if the file exists and creates empty one if needed. Do you think loki should create file for the user in load() when one does not exists?

**Comment by techfort** [comment] 2015-01-20 11:01
I think this is a good suggestion. I'm inclined to close this issue and open a new one though as it's kind of unrelated, if that's ok with you @teef

**Comment by teef** [comment] 2015-01-20 12:27
Sure. Will you do it?

2015-01-20 12:01 GMT+01:00 Techfort <notifications@github.com>:

> I think this is a good suggestion. I'm inclined to close this issue and
> open a new one though as it's kind of unrelated, if that's ok with you
> @teef <https://github.com/teef>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/techfort/LokiJS/issues/60#issuecomment-70637309>.
>



-- 
Tomasz Fidecki

**Comment by techfort** [comment] 2015-01-20 12:59
Absolutely, just waiting for your confirmation. Closing this, issue opened here https://github.com/techfort/LokiJS/issues/61

**Closed by techfort** 2015-01-20 12:59 UTC

**Comment by retorquere** [comment] 2015-09-25 21:44
I am hitting a similar problem. I have a custom adapter, loaded with

```
var db = new loki('serialized', {adapter: myAdapter, env: 'BROWSER'});
coll = db.addCollection('serialized', { indices: ['itemID', 'uri'] })
```

(is that the correct syntax? It seems to work) but I'm getting

```
TypeError: cyclic object value
    ===== Stack Trace =====
    Loki.prototype.serialize:1:8015
```

The DB objects do not themselves have circular references.

**Comment by retorquere** [comment] 2015-09-25 21:49
Would it be a signifiant performance hit to just load the data myself and feed the DB myself? This would probably be relatively small by LokiJS standards -- I've never seen more than 30k items in a DB.

If I were to do this, could I just insert objects that already have `$loki/meta` vars? Is collection.data a safe way to get to the collection items?

**Comment by retorquere** [comment] 2015-09-25 21:50
(I meant load/save, not just load)

**Comment by obeliskos** [comment] 2015-09-25 22:22
What kind of adapter are you using and are doing manual loadDatabase and saveDatabase calls?  Are you using an older version of loki?  We fixed a similar serialization error a few weeks/month ago.  If there is an exception occurring in loki serialize and its our objects I would like to fix.

Since you are using this in a github project to i'm hesitant to lead you down bad practice routes.  Is this difficult to reproduce?  You can use loki sandbox to create example and post as gist or use plunker?  If not let me know and i'll try to provide options.

**Comment by retorquere** [comment] 2015-09-26 10:30
I'm using the version from https://raw.githubusercontent.com/techfort/LokiJS/master/build/lokijs.min.js, not older than a week.

I've put the adapter code in a gist here https://gist.github.com/422ac2fff3a108e60207 ; it's fairly trivial (it has other methods, but not related to adapterness), but it doesn't actually get called, as the error occurs during serialization, not save.

I'll see if I can get an MWE going, the current code is part of a Zotero extension, which is a peculiar environment. I don't think the environment is a relevant influence in this case, but a non-zotero MWE ought to be easier to debug.

What is plunker?

**Comment by retorquere** [comment] 2015-09-26 10:30
Should I open a new issue for this BTW?

**Comment by obeliskos** [comment] 2015-09-26 13:03
I think your adapter implementation for loadDatabase might be wrong.  Since our adapters are sometimes synchronous and sometimes asynchronous, we use callback to pass return value.  So maybe alter your loadDatabase to be something like : 

```javascript
loadDatabase: function(name, callback) { 
  var e, serialized; 
  try { 
    serialized = Zotero.BetterBibTeX.createFile('serialized-items.json'); 
    if (!serialized.exists()) { 
      callback(null); 
    } 
    callback(Zotero.File.getContents(serialized)); 
  } catch (_error) { 
    e = _error; 
    throw new Error(Zotero.BetterBibTeX.debug("serialized.loadDatabase failed: " + e); 
  } 
} 
```

**Comment by retorquere** [comment] 2015-09-26 13:24
Is the loadDatabase *required* to be async? http://lokijs.org/#/docs#indexedadapter says "callback: (optional) the callback handler". I don't need async.

**Comment by obeliskos** [comment] 2015-09-26 13:42
Well looking over the source it would appear you are required to implement your adapter using the callback method i described.  

The callback only seems to be optional when calling the loki database's loadDatabase method, which in turn calls your adapter loadDatabase (and expects that callback).

We probably need to change that in the loki docs web page you referenced.

Since your adapter is not async we are just simulating async behavior via a callback... its still fundamentally synchronous.

**Comment by retorquere** [comment] 2015-09-26 19:02
That's an easy change to make, so thanks for that tip, but I'm hitting the cyclic error on save, in the phase where LokiJS serializes, which I think happens before my adapter is called, right?

**Comment by retorquere** [comment] 2015-09-26 19:53
I'll be darned if I know why, but having loadDatabase call the callback as @obeliskos described fixes the loadDatabase invocation. Thanks!

**Comment by obeliskos** [comment] 2015-09-26 20:02
Does both save and load work?  When user code calls db.loadDatabase(), our generic loadDatabase calls adapter loadDatabase and expects it to use our callback we pass to it. 

If still have any cyclic stuff you might try : 
- create new loki('test') and immediately console.log(db.serialize());  should get some json in console

If that works you can try creating empty collections and calling serialize() and see if that causes error.

**Comment by retorquere** [comment] 2015-09-26 20:58
I can load what I saved. Sorry for the noise. In saveDatabase, I call `callback(true);` which seems to work.

**Comment by obeliskos** [comment] 2015-09-26 22:53
Ah, glad you got it working, I'll see if @techfort can refine wording in lokijs.org docs.

**Comment by rockneverdies55** [comment] 2016-04-01 00:59
Just putting here as a reference in the case if people come here from a google search...

I had a similar issue because of using underscore extend function. Something like the following was causing the issue:

```
var settings = require('../settings.js');

var settingsCOL = db.addCollection('settings');
settingsCOL.insert(_.extend({title: 'appSettings'}, settings));

```
